-- MySQL Script generated by MySQL Workbench
-- Seg 10 Jun 2019 09:52:03 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_vendas` DEFAULT CHARACTER SET utf8 ;
USE `db_vendas` ;

-- -----------------------------------------------------
-- Table `db_vendas`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`municipios` (
  `MUN_CODIGO` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `MUN_NOME` VARCHAR(150) NOT NULL,
  `MUN_UF_ESTADO` VARCHAR(2) NOT NULL,
  `MUN_CEP` VARCHAR(8) NULL,
  PRIMARY KEY (`MUN_CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`clientes` (
  `CLI_CODIGO` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CLI_MUN_CODIGO` INT(4) UNSIGNED NOT NULL,
  `CLI_NOME` VARCHAR(50) NOT NULL,
  `CLI_DATA_NASCIMENTO` DATETIME NOT NULL,
  `CLI_SEXO` VARCHAR(1) NULL,
  `CLI_CPF` VARCHAR(11) NULL,
  `CLI_RG` VARCHAR(9) NULL,
  `CLI_CNPJ` VARCHAR(14) NULL,
  `CLI_ENDERECO` VARCHAR(100) NULL,
  `CLI_EMAIL` VARCHAR(50) NULL,
  `CLI_DATA_CADASTRO` DATETIME NOT NULL,
  `CLI_TIPO` VARCHAR(1) NOT NULL,
  `CLI_STATUS` VARCHAR(1) NULL,
  `CLI_FONE` VARCHAR(20) NULL,
  `CLI_NOME_CONTATO` VARCHAR(50) NULL,
  PRIMARY KEY (`CLI_CODIGO`),
  INDEX `fk_clientes_municipios1_idx` (`CLI_MUN_CODIGO` ASC),
  CONSTRAINT `fk_clientes_municipios1`
    FOREIGN KEY (`CLI_MUN_CODIGO`)
    REFERENCES `db_vendas`.`municipios` (`MUN_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`fornecedores` (
  `FOR_CODIGO` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FOR_MUN_CODIGO` INT(4) UNSIGNED NOT NULL,
  `FOR_RAZAO_SOCIAL` VARCHAR(100) NOT NULL,
  `FOR_NOME_FANTASIA` VARCHAR(50) NOT NULL,
  `FOR_NOME_CONTATO` VARCHAR(50) NOT NULL,
  `FOR_CNPJ` VARCHAR(14) NOT NULL,
  `FOR_ENDERECO` VARCHAR(100) NULL,
  `FOR_DATA_CADASTRO` DATETIME NULL,
  `FOR_FONE` VARCHAR(20) NULL,
  `FOR_EMAIL` VARCHAR(50) NULL,
  `FOR_WEBSITE` VARCHAR(100) NULL,
  PRIMARY KEY (`FOR_CODIGO`),
  INDEX `fk_fornecedores_municipios1_idx` (`FOR_MUN_CODIGO` ASC),
  CONSTRAINT `fk_fornecedores_municipios1`
    FOREIGN KEY (`FOR_MUN_CODIGO`)
    REFERENCES `db_vendas`.`municipios` (`MUN_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`categorias_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`categorias_produtos` (
  `CAT_CODIGO` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CAT_IDENTIFICADOR` VARCHAR(4) NULL,
  `CAT_DESCRICAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CAT_CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`produtos` (
  `PRO_CODIGO` INT(5) NOT NULL AUTO_INCREMENT,
  `PRO_FOR_CODIGO` INT(5) UNSIGNED NOT NULL,
  `PRO_CAT_CODIGO` INT(4) UNSIGNED NOT NULL,
  `PRO_DESCRICAO` VARCHAR(100) NOT NULL,
  `PRO_QNT_DISPONIVEL` INT(5) NULL,
  `PRO_ULTIMA_AQUISICAO` DATETIME NULL,
  `PRO_VALOR_UNIT` FLOAT NULL,
  `PRO_FABRICANTE` VARCHAR(50) NULL,
  `PRO_DETALHES` TEXT NULL,
  PRIMARY KEY (`PRO_CODIGO`),
  INDEX `fk_produtos_fornecedores1_idx` (`PRO_FOR_CODIGO` ASC),
  INDEX `fk_produtos_categorias_produtos1_idx` (`PRO_CAT_CODIGO` ASC),
  CONSTRAINT `fk_produtos_fornecedores1`
    FOREIGN KEY (`PRO_FOR_CODIGO`)
    REFERENCES `db_vendas`.`fornecedores` (`FOR_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_categorias_produtos1`
    FOREIGN KEY (`PRO_CAT_CODIGO`)
    REFERENCES `db_vendas`.`categorias_produtos` (`CAT_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`atendentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`atendentes` (
  `ATE_CODIGO` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ATE_NOME` VARCHAR(100) NULL,
  `ATE_ULTIMO_ACESSO` DATETIME NULL,
  `ATE_RAMAL` VARCHAR(4) NOT NULL,
  `ATE_EMAIL` VARCHAR(50) NOT NULL,
  `ATE_PERFIL` VARCHAR(1) NOT NULL,
  `ATE_STATUS` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ATE_CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`bancos` (
  `BAN_CODIGO` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `BAN_NOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`BAN_CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`vendas` (
  `VEN_CODIGO` INT(5) NOT NULL AUTO_INCREMENT,
  `VEN_CLI_CODIGO` INT(5) UNSIGNED NOT NULL,
  `VEN_ATE_CODIGO` INT(5) UNSIGNED NOT NULL,
  `VEN_BAN_CODIGO` INT(3) UNSIGNED NOT NULL,
  `VEN_VALOR_TOTAL` FLOAT NOT NULL,
  `VEN_FORMA_PAGAMENTO` VARCHAR(1) NULL,
  `VEN_OBSERVACOES` VARCHAR(255) NULL,
  PRIMARY KEY (`VEN_CODIGO`),
  INDEX `fk_vendas_clientes1_idx` (`VEN_CLI_CODIGO` ASC),
  INDEX `fk_vendas_atendentes1_idx` (`VEN_ATE_CODIGO` ASC),
  INDEX `fk_vendas_bancos1_idx` (`VEN_BAN_CODIGO` ASC),
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`VEN_CLI_CODIGO`)
    REFERENCES `db_vendas`.`clientes` (`CLI_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_atendentes1`
    FOREIGN KEY (`VEN_ATE_CODIGO`)
    REFERENCES `db_vendas`.`atendentes` (`ATE_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_bancos1`
    FOREIGN KEY (`VEN_BAN_CODIGO`)
    REFERENCES `db_vendas`.`bancos` (`BAN_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`tipo_mensagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`tipo_mensagens` (
  `TMS_CODIGO` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TMS_DESCRICAO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TMS_CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`mensagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`mensagens` (
  `MEN_CODIGO` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `MEN_ATE_CODIGO` INT(5) UNSIGNED NOT NULL,
  `MEN_TMS_CODIGO` INT(3) UNSIGNED NOT NULL,
  `MEN_TEXTO` TEXT NOT NULL,
  `MEN_DATA_ENVIO` DATETIME NULL,
  PRIMARY KEY (`MEN_CODIGO`),
  INDEX `fk_mensagens_atendentes1_idx` (`MEN_ATE_CODIGO` ASC),
  INDEX `fk_mensagens_tipo_mensagens1_idx` (`MEN_TMS_CODIGO` ASC),
  CONSTRAINT `fk_mensagens_atendentes1`
    FOREIGN KEY (`MEN_ATE_CODIGO`)
    REFERENCES `db_vendas`.`atendentes` (`ATE_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensagens_tipo_mensagens1`
    FOREIGN KEY (`MEN_TMS_CODIGO`)
    REFERENCES `db_vendas`.`tipo_mensagens` (`TMS_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vendas`.`hist_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vendas`.`hist_vendas` (
  `HVE_VEN_CODIGO` INT(5) NOT NULL,
  `HVE_PRO_CODIGO` INT(5) NOT NULL,
  `HVE_DATA_VENDA` DATETIME NOT NULL,
  `HVE_DATA_RECEBIMENTO` DATETIME NULL,
  `HVE_QNT_ITENS` INT(5) NULL,
  PRIMARY KEY (`HVE_VEN_CODIGO`, `HVE_PRO_CODIGO`),
  INDEX `fk_hist_vendas_produtos1_idx` (`HVE_PRO_CODIGO` ASC),
  CONSTRAINT `fk_hist_vendas_vendas1`
    FOREIGN KEY (`HVE_VEN_CODIGO`)
    REFERENCES `db_vendas`.`vendas` (`VEN_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hist_vendas_produtos1`
    FOREIGN KEY (`HVE_PRO_CODIGO`)
    REFERENCES `db_vendas`.`produtos` (`PRO_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
